### ISSUE TITLE
Cannot build on CentOS 6.5

### ISSUE THREAD

**Issue by piffio** [mirage/mirage-www#230]
I'm trying to get into MirageOS by following the instructions / tutorial on http://openmirage.org

I was trying to build the mirage-www package on a CentOS 6.5 VM, and this is the error I get into:

```
[vagrant@centos65 src]$ mirage config --unix
Mirage      Using scanned config file: config.ml
Mirage      Processing: /home/vagrant/src/mirage-www/src/config.ml
Mirage      => rm -rf /home/vagrant/src/mirage-www/src/_build/config.*
Mirage      => cd /home/vagrant/src/mirage-www/src && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
Mirage       ocamlfind ocamldep -package mirage -modules config.ml > config.ml.depends
Mirage       ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
Mirage       + ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
Mirage       File "config.ml", line 57, characters 2-16:
Mirage       Error: Unbound value conduit_direct
Mirage       Command exited with code 2.
[ERROR]      The command "cd /home/vagrant/src/mirage-www/src && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs" exited with code 10.
```

Attached some additional information about the enviromnent:

Ocaml version:

```
[vagrant@centos65 src]$ ocaml -version
The OCaml toplevel, version 4.01.0
```

Opam packages installed:

```
[vagrant@centos65 src]$ opam list
Installed packages for system:
base-bigarray             base  Bigarray library distributed with the OCaml compiler
base-bytes              legacy  Bytes compatibility library distributed with ocamlfind
base-no-ppx               base  A pseudo-library to indicate lack of extension points support
base-threads              base  Threads library distributed with the OCaml compiler
base-unix                 base  Unix library distributed with the OCaml compiler
base64                   1.0.0  Base64 encoding and decoding library
camlp4                  4.01.0  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner                 0.9.5  Declarative definition of command line interfaces for OCaml
cohttp                  0.10.1  HTTP library for Lwt, Async and Mirage
cstruct                  1.4.0  access C structures via a camlp4 extension
dns                     0.10.0  DNS client and server implementation
fieldslib            109.20.03  Syntax extension to define first class values representing record fields, to get and set record fields, iterate and fold over all fields of a record and create new record values
io-page                  1.1.1  Allocate memory pages suitable for aligned I/O
ipaddr                   2.5.0  IP (and MAC) address representation library
lwt                      2.4.6  A cooperative threads library for OCaml
mirage                   1.2.0  The Mirage library operating system
mirage-block-unix        1.2.1  Mirage disk block driver for Unix
mirage-clock-unix        1.0.0  A Mirage-compatible Clock library for Unix
mirage-console-unix      1.0.0  A Mirage-compatible Console library for Unix
mirage-http              1.1.0  Mirage HTTP client and server driver for Unix
mirage-net-unix          1.1.1  Ethernet network driver for Mirage, using tuntap
mirage-types             1.2.0  Module type definitions for Mirage-compatible applications
mirage-unix              1.1.0  Mirage OS library for Unix compilation
ocamlfind                1.5.3  A library manager for OCaml
ocplib-endian              0.7  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
optcomp                    1.6  Optional compilation with cpp-like directives
ounit                    2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing frameworks
re                       1.2.2  RE is a regular expression library for OCaml
sexplib              111.25.00  Library for serializing OCaml values to and from S-expressions
shared-memory-ring       1.1.0  Shared memory rings for RPC and bytestream communications.
ssl                      0.4.7  Bindings for OpenSSL
stringext                1.0.0  Extra string functions for OCaml
tcpip                    1.1.6  Userlevel TCP/IP stack
tuntap                   1.0.0  TUN/TAP bindings
type_conv            111.13.00  Library for building type-driven syntax extensions
uri                      1.7.2  RFC3986 URI/URL parsing library
vchan                    2.0.0  Xen Vchan implementation
xenstore                 1.2.5  Xenstore protocol clients and server
```

I tried to install the conduit package, but it fails rebuilding the `mirage-console-unix.1.0.0` package due to what I believe is an incompatibility with `mirage-types-2.0.0` that seems to be required by conduit.

More details here:

```
[vagrant@centos65 src]$ opam install conduit
The following actions will be performed:
 - install base64.1.0.0 [required by conduit]
 - install xenstore.1.2.5 [required by conduit]
 - upgrade mirage-types.1.2.0 to 2.0.0 [required by conduit]
 - install dns.0.10.0 [required by conduit]
 - recompile mirage.1.2.0 [use mirage-types]
 - recompile mirage-block-unix.1.2.1 [use mirage-types]
 - recompile mirage-clock-unix.1.0.0 [use mirage-types]
 - recompile mirage-net-unix.1.1.1 [use mirage-types]
 - install vchan.2.0.0 [required by conduit]
 - recompile mirage-unix.1.1.0 [use mirage-types]
 - recompile mirage-console-unix.1.0.0 [use mirage-types]
 - recompile tcpip.1.1.6 [use mirage-types]
 - install conduit.0.6.0
 - recompile mirage-http.1.1.0 [use mirage-types]
5 to install | 8 to reinstall | 1 to upgrade | 0 to downgrade | 0 to remove

....


===== ERROR while recompiling mirage-console-unix.1.0.0 =====
# opam-version 1.1.1
# os           linux
# command      make unix-install
# path         /home/vagrant/ocamlbrew/ocaml-4.01.0/.opam/system/build/mirage-console-unix.1.0.0
# compiler     system (4.01.0)
# exit-code    2
# env-file     /home/vagrant/ocamlbrew/ocaml-4.01.0/.opam/system/build/mirage-console-unix.1.0.0/mirage-console-unix-19919-f589c9.env
# stdout-file  /home/vagrant/ocamlbrew/ocaml-4.01.0/.opam/system/build/mirage-console-unix.1.0.0/mirage-console-unix-19919-f589c9.out
# stderr-file  /home/vagrant/ocamlbrew/ocaml-4.01.0/.opam/system/build/mirage-console-unix.1.0.0/mirage-console-unix-19919-f589c9.err
### stdout ###
# ...[truncated]
# ocamlfind ocamlc -c -package mirage-unix -package mirage-types -I unix -o unix/console.cmo unix/console.ml
# + ocamlfind ocamlc -c -package mirage-unix -package mirage-types -I unix -o unix/console.cmo unix/console.ml
# File "unix/console.ml", line 1:
# Error: The implementation unix/console.ml
#        does not match the interface unix/console.cmi:
#        The field `close' is required but not provided
#        The field `writev' is required but not provided
#        The field `read' is required but not provided
#        The field `buffer' is required but not provided
# Command exited with code 2.
### stderr ###
# ocamlfind: [WARNING] No such directory: /home/vagrant/ocamlbrew/ocaml-4.01.0/.opam/system/lib/mirage-console-unix
# ocamlfind: _build/unix/mirage-console.cmxs: No such file or directory
# make: *** [unix-install] Error 2
```

Let me know if you need more details
